#!/usr/bin/env bash
# Prints according to instruction

ter=1
while [ $ter -lt 21 ]; do
	echo $ter
	case "$ter" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( ter++ ))
done
